# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DH Bridge
email: bridgingdh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Encouraging Computational Thinking and Digital Skills in the Humanities
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dhbridge.org" # the base hostname & protocol for your site
twitter_username: dhbridge
github_username:  dhbridge

# Build settings
markdown: kramdown